version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    open-pull-requests-limit: 5
    ignore:
      # Ignore major version updates for packages that might break Node.js compatibility
      - dependency-name: '*'
        update-types: ['version-update:semver-major']
    commit-message:
      prefix: 'chore'
      prefix-development: 'chore'
      include: 'scope'
    versioning-strategy: increase
    groups:
      # Group all dev dependencies updates together
      development-dependencies:
        dependency-type: 'development'
        update-types:
          - 'minor'
          - 'patch'
      # Group all production dependencies updates together
      production-dependencies:
        dependency-type: 'production'
        update-types:
          - 'minor'
          - 'patch'
